name: CI
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v4
      with:
        path: "1.4.328.1"
        key: vulkansdk-ubuntu-24.04-arm-1.4.328.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/IanET/vulkan-sdk-arm/releases/download/1.4.328.1/vulkansdk-ubuntu-24.04-arm-1.4.328.1.tar.xz?Human=true -O vulkansdk-ubuntu-24.04-arm-1.4.328.1.tar.xz
        tar -xf vulkansdk-ubuntu-24.04-arm-1.4.328.1.tar.xz
        # rm -rf 1.4.328.1/source 1.4.328.1/samples
        find 1.4.328.1 -type f | grep -v -E 'vulkan|glslang' | xargs rm
    - name: build
      run: |
        export VULKAN_SDK=`pwd`/1.4.328.1/aarch64
        mkdir build && cd build
        cmake ../src
        cmake --build . -j 2
