name: CI
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v4
      with:
        path: "C:/VulkanSDK/1.4.328.1"
        key: vulkansdk-windows-X64-1.4.328.1
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.4.328.1/windows/vulkansdk-windows-X64-1.4.328.1.exe?Human=true -OutFile vulkansdk-windows-X64-1.4.328.1.exe
        # 7z x -aoa ./vulkansdk-windows-X64-1.4.328.1.exe -oVulkanSDK
        # Remove-Item .\VulkanSDK\Demos, .\VulkanSDK\Samples, .\VulkanSDK\Third-Party, .\VulkanSDK\Tools, .\VulkanSDK\Tools32, .\VulkanSDK\Bin32, .\VulkanSDK\Lib32 -Recurse
        ./vulkansdk-windows-X64-1.4.328.1.exe in --al --da --confirm-command
        # dir C:\VulkanSDK\1.4.328.1
    - name: build
      run: |
        $env:VULKAN_SDK="C:\VulkanSDK\1.4.328.1"
        setx VULKAN_SDK "C:\VulkanSDK\1.4.328.1"
        mkdir build; cd build
        cmake -A x64 ../src
        cmake --build . --config Release -j 2

